LANGUAGES = {
    "English": {
        # Sidebar Settings & Costs
        "currency_settings": "⚙️ Currency & Settings",
        "currency": "Currency",
        "exchange_rate": "Exchange rate",
        "costs": "💰 Costs",
        "electricity": "Electricity",
        "water": "Water",
        "waste_handling": "Waste handling",
        "chem_a": "Chemical A",
        "chem_b": "Chemical B",
        "chem_c": "Chemical C",
        "fabric_waste_cost": "Fabric waste cost",
        "co2_factor": "CO₂ Emissions Factor (kg CO₂/kWh)",
        "co2_help": "Emissions factor in kg CO2 per consumed kWh electricity.",
        "investment_cost": "Total Investment Cost",
        
        # Main Page
        "app_title": "📊 F-Max ROI & Sustainability Calculator",
        "gen_prod_data": "📋 General Production Data",
        "fabric_width": "Fabric width (m)",
        "fabric_weight_sqm": "Fabric weight (kg/sqm)",
        "fabric_weight_lm": "Fabric weight / linear meter (kg)",
        "prod_speed": "Production speed (m/min)",
        "drying_energy": "Drying power kWh / kg fabric @100% pickup",
        "working_hours": "Working hours per day (h)",
        "working_days": "Working days per year",
        "changeovers_day": "Changeovers / day",
        
        # Recipe & Application
        "recipe_data": "🧪 Recipe & Application Data",
        "trad_padder": "Traditional Padder",
        "padder_pickup": "Padder Pickup (%)",
        "operating_energy": "Operating Energy (kW)",
        "waste_changeover": "Waste at changeover (L)",
        "fabric_waste_changeover": "Fabric waste at changeover (m)",
        "changeover_time": "Changeover time (min)",
        "applied_chem_info": "Applied chemical per kg of fabric",
        "at_pickup": "at",
        "pickup": "pickup",
        
        "imogo_fmax": "Imogo F-Max",
        "fmax_pickup": "F-Max Pickup (%)",
        "chem_reduction": "Chemical Reduction (%)",
        "target_conc_info": "Target concentration for equal add-on (Excluding possible reduction):",
        
        # Summaries & Results
        "prod_summary": "📊 Production Volume Summary",
        "kg_year": "kg/year",
        "m_year": "m/year",
        "kg_day": "kg/day",
        "m_day": "m/day",
        "extra": "extra",
        
        "capacity_boost_title": "🚀 Potential Capacity Boost (At Equal Energy Cost)",
        "capacity_boost_desc": "By utilizing the lower wet pickup of the F-max, you can choose to either **save energy** or run the stenter significantly faster for the **exact same energy cost** as your current padder. Here is your theoretical production increase:",
        "max_potential_speed": "Max Potential Speed",
        "extra_vol_weight": "Extra Volume (Weight)",
        "extra_vol_length": "Extra Volume (Length)",
        
        "savings_overview": "📈 Savings Overview",
        "annual_savings": "Annual Savings",
        "payback_period": "Payback Period",
        "months": "months",
        "chem_savings": "Chemistry Savings",
        
        "env_savings": "🌍 Environmental Savings",
        "water_savings": "Water Savings",
        "co2_savings": "CO₂ Savings",
        "energy_savings": "Energy Savings",
        "tonnes_year": "tonnes/year",
        
        "monetary_savings": "💰 Monetary Savings Breakdown",
        "category": "Category",
        "savings": "Savings",
        "process_water": "Process Water",
        "waste_water_treatment": "Waste Water Treatment",
        "fabric_waste": "Fabric Waste",
        "energy": "Energy",
        "total_annual_savings": "Total Annual Savings",
        
        "total_cost_kg": "💰 Total Cost per kg Fabric",
        
        # Visuals
        "visual_overview": "📊 Visual Savings Overview",
        "yearly_savings_cat": "Yearly savings per category",
        "system": "System",
        
        # HTML Report
        "gen_report": "📄 Generate Report",
        "report_title": "Imogo F-Max ROI & Environmental Report",
        "prepared_for": "Prepared for:",
        "generated": "Generated:",
        "key_results": "Key Results",
        "prod_summary_report": "Production Summary",
        "prod_volume": "Production Volume",
        "physical_savings": "Physical Savings",
        "process_recipe_comp": "Process & Recipe Comparison",
        "gen_params": "General Parameters & Unit Costs",
        "parameter": "Parameter",
        "value": "Value",
        "dl_report": "📥 Download Report as HTML (Print → Save as PDF)",
        "footer_text": "This report was automatically generated by the Imogo F-Max ROI Calculator."
    },
    
    "Português (Brasil)": {
        # Sidebar Settings & Costs
        "currency_settings": "⚙️ Moeda e Configurações",
        "currency": "Moeda",
        "exchange_rate": "Taxa de Câmbio",
        "costs": "💰 Custos",
        "electricity": "Eletricidade",
        "water": "Água",
        "waste_handling": "Tratamento de Efluentes",
        "chem_a": "Químico A",
        "chem_b": "Químico B",
        "chem_c": "Químico C",
        "fabric_waste_cost": "Custo de descarte de tecido",
        "co2_factor": "Fator de Emissão de CO₂ (kg CO₂/kWh)",
        "co2_help": "Fator de emissão em kg CO2 por kWh de eletricidade consumida.",
        "investment_cost": "Custo Total de Investimento",
        
        # Main Page
        "app_title": "📊 Calculadora de ROI e Sustentabilidade F-Max",
        "gen_prod_data": "📋 Dados Gerais de Produção",
        "fabric_width": "Largura do tecido (m)",
        "fabric_weight_sqm": "Gramatura do tecido (kg/m²)",
        "fabric_weight_lm": "Peso do tecido / metro linear (kg)",
        "prod_speed": "Velocidade de produção (m/min)",
        "drying_energy": "Energia de secagem kWh / kg tecido @100% pick-up",
        "working_hours": "Horas de trabalho por dia (h)",
        "working_days": "Dias de trabalho por ano",
        "changeovers_day": "Trocas / dia",
        
        # Recipe & Application
        "recipe_data": "🧪 Dados de Receita e Aplicação",
        "trad_padder": "Foulard Convencional",
        "padder_pickup": "Pick-up Foulard (%)",
        "operating_energy": "Energia de Operação (kW)",
        "waste_changeover": "Descarte na troca (L)",
        "fabric_waste_changeover": "Descarte de tecido na troca (m)",
        "changeover_time": "Tempo de troca (min)",
        "applied_chem_info": "Químico aplicado por kg de tecido",
        "at_pickup": "com",
        "pickup": "de pick-up",
        
        "imogo_fmax": "Imogo F-Max",
        "fmax_pickup": "Pick-up F-Max (%)",
        "chem_reduction": "Redução Química (%)",
        "target_conc_info": "Concentração alvo para aplicação igual (excluindo possível redução):",
        
        # Summaries & Results
        "prod_summary": "📊 Resumo do Volume de Produção",
        "kg_year": "kg/ano",
        "m_year": "m/ano",
        "kg_day": "kg/dia",
        "m_day": "m/dia",
        "extra": "extra",
        
        "capacity_boost_title": "🚀 Aumento Potencial de Capacidade (Com o mesmo custo de energia)",
        "capacity_boost_desc": "Ao utilizar o pick-up reduzido da F-max, você pode optar por **economizar energia** ou operar a rama consideravelmente mais rápido pelo **exato mesmo custo de energia** do seu foulard atual. Aqui está o seu aumento de produção teórico:",
        "max_potential_speed": "Velocidade Máxima Potencial",
        "extra_vol_weight": "Volume Extra (Peso)",
        "extra_vol_length": "Volume Extra (Comprimento)",
        
        "savings_overview": "📈 Resumo de Economia",
        "annual_savings": "Economia Anual",
        "payback_period": "Período de Payback",
        "months": "meses",
        "chem_savings": "Economia Química",
        
        "env_savings": "🌍 Economia Ambiental",
        "water_savings": "Economia de Água",
        "co2_savings": "Economia de CO₂",
        "energy_savings": "Economia de Energia",
        "tonnes_year": "toneladas/ano",
        
        "monetary_savings": "💰 Detalhamento da Economia Financeira",
        "category": "Categoria",
        "savings": "Economia",
        "process_water": "Água de Processo",
        "waste_water_treatment": "Tratamento de Efluentes",
        "fabric_waste": "Descarte de Tecido",
        "energy": "Energia",
        "total_annual_savings": "Economia Anual Total",
        
        "total_cost_kg": "💰 Custo Total por kg de Tecido",
        
        # Visuals
        "visual_overview": "📊 Visão Geral Visual da Economia",
        "yearly_savings_cat": "Economia anual por categoria",
        "system": "Sistema",
        
        # HTML Report
        "gen_report": "📄 Gerar Relatório",
        "report_title": "Relatório de ROI e Ambiental Imogo F-Max",
        "prepared_for": "Preparado para:",
        "generated": "Gerado em:",
        "key_results": "Principais Resultados",
        "prod_summary_report": "Resumo de Produção",
        "prod_volume": "Volume de Produção",
        "physical_savings": "Economia Física",
        "process_recipe_comp": "Comparação de Processo e Receita",
        "gen_params": "Parâmetros Gerais e Custos Unitários",
        "parameter": "Parâmetro",
        "value": "Valor",
        "dl_report": "📥 Baixar Relatório em HTML (Imprimir → Salvar como PDF)",
        "footer_text": "Este relatório foi gerado automaticamente pela Calculadora de ROI Imogo F-Max."
    }
}